# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('subject', models.CharField(max_length=150, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Adresse')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Code postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(max_length=75, verbose_name='Pays')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Numéro de téléphone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('constructor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Constructeur')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Année de sortie')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/uploaded/img/shop/', verbose_name='Jaquette')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Prix')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Developer', verbose_name='Développeur')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Editor', verbose_name='Éditeur')),
                ('genres', models.ManyToManyField(to='shop.Genre', verbose_name='Genres')),
                ('platforms', models.ManyToManyField(to='shop.Platform', verbose_name='Plateformes')),
            ],
        ),
    ]
