# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=5, verbose_name='Code postal'),
        ),
    ]
