# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171009_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('subject', models.CharField(max_length=150, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
